/* Speculative Antennology — rhizomatic field app.
   A pannable 2D plane. Islands are placed at absolute (x, y); nothing is
   numbered, very little is titled, metadata is mostly stripped. Movement is
   free in both axes; threads connect islands by association. */

const TWEAK_DEFAULTS = /*EDITMODE-BEGIN*/{
  "density": "regular",
  "grid": true,
  "numbering": "arabic",
  "threads": true,
  "autoRotate": true
}/*EDITMODE-END*/;

const ARCHIVE = window.SA_ARCHIVE || [];

const VIEWER_SPECIMENS = [
  { i: 80, meshIdx: 37   },
  { i: 81, meshIdx: 154  },
  { i: 82, meshIdx: 321  },
  { i: 83, meshIdx: 498  },
  { i: 84, meshIdx: 780  },
  { i: 85, meshIdx: 1012 },
  { i: 86, meshIdx: 1333 },
  { i: 87, meshIdx: 1604 },
  { i: 88, meshIdx: 1870 },
  { i: 89, meshIdx: 2099 },
  { i: 90, meshIdx: 2287 },
  { i: 91, meshIdx: 2440 },
];

// ───────────────────────────────────────────────────────────────────────────
// Archive photograph plate — cycles through 48 real images

function Plate({ n }){
  const idx = (n - 1).toString().padStart(2, '0');
  return (
    <img
      src={`assets/archive/ant-${idx}.jpg`}
      alt=""
      style={{ display:'block', width:'100%', height:'100%', objectFit:'cover',
               filter:'grayscale(1) contrast(1.05)' }}
    />
  );
}

// ───────────────────────────────────────────────────────────────────────────
// Layout — absolute coords in the infinite plane. No section order.
// Organized loosely into zones so threads read, but with no TOC surface.
// (0,0) is the title; negative/positive in both axes.

const ISLANDS = (function(){
  const items = [];

  // Notion-driven stable-ID islands. Sourced from data/islands.generated.js
  // which is regenerated by tools/sync-from-notion.mjs (and on a cron in CI).
  if (Array.isArray(window.SA_ISLANDS)) {
    for (const it of window.SA_ISLANDS) items.push(it);
  }

  // Dynamic islands — not Notion-tracked.
  items.push({ id: "viewer", kind: "viewer", x: 420, y: 220, w: 640 });
  items.push({ id: "arc-head", kind: "cluster-head",
    x: -600, y: 1400, k: "archive", n: "gathered · ongoing"
  });

  // Archive thumbs — seeded pseudo-random distribution
  let seed = 97;
  const rand = ()=>{ seed = (seed * 1664525 + 1013904223) >>> 0; return seed / 4294967296; };
  for (const a of ARCHIVE){
    const col = (a.i - 1) % 10;
    const row = Math.floor((a.i - 1) / 10);
    const jx = (rand() - 0.5) * 80;
    const jy = (rand() - 0.5) * 60;
    const baseX = -600 + col * 170 + jx;
    const baseY = 1680 + row * 220 + jy;
    items.push({ id: "arc-"+a.i, kind: "thumb",
      x: baseX, y: baseY, w: 120, a
    });
  }

  // Featured specimens — larger cards near the archive header
  for (let k = 0; k < 4; k++){
    const a = ARCHIVE[[0, 16, 35, 47][k]];
    items.push({ id: "sp-"+a.i, kind: "spec",
      x: -1400 + k * 260, y: 1480, w: 220, a
    });
  }

  return items;
})();

// Threads = Notion-driven (between stable islands) + dynamic (involving
// viewer / arc-head / sp-* — non-Notion islands).
const THREADS = [
  ...(Array.isArray(window.SA_THREADS_FROM_NOTION) ? window.SA_THREADS_FROM_NOTION : []),
  // Dynamic — at least one endpoint is not Notion-tracked.
  ["ess-6", "viewer"],
  ["title", "viewer"],
  ["viewer", "arc-head"],
  ["viewer", "sp-17"],
  ["field-1", "arc-head"],
  ["arc-head", "sp-1"],
  ["arc-head", "sp-17"],
  ["arc-head", "sp-36"],
  ["arc-head", "sp-48"],
  ["gl-2", "arc-head"],
  ["gl-4", "arc-head"],
  ["pq-1", "viewer"],
  ["wh-2", "viewer"],
  ["colophon", "arc-head"],
  ["pq-3", "arc-head"],
];

// ───────────────────────────────────────────────────────────────────────────
// Islands

function Island({ it, viewer }){
  const style = { left: it.x + "px", top: it.y + "px", width: it.w + "px" };

  if (it.kind === "title") {
    return (
      <div className="island title" style={style} data-id={it.id}>
        <h1>Speculative<br/><em>Antennology</em></h1>
        <div className="sub">
          a field of found and computed radiators; notes on the shape of antennas and the persistence of the electromagnetic trace.
        </div>
        <div className="auth">
          <span>Yanai Toister <span className="aff">Tampere</span></span>
          <span>Nimrod Astarhan <span className="aff">independent</span></span>
        </div>
      </div>
    );
  }

  if (it.kind === "prose") {
    return (
      <div className="island prose-frag" style={style} data-id={it.id}>
        <div className="body">
          {it.lede
            ? <p className="lede" dangerouslySetInnerHTML={{__html: "&ldquo;"+it.text+"&rdquo;"}}/>
            : <p dangerouslySetInnerHTML={{__html: it.text}}/>
          }
          {it.cite && <p style={{fontFamily:"var(--f-grot)", fontSize:"10px", letterSpacing:".12em", textTransform:"uppercase", color:"var(--muted)", marginTop:".6rem"}}>— {it.cite}</p>}
        </div>
      </div>
    );
  }

  if (it.kind === "pullquote") {
    return (
      <div className="island pullquote" style={style} data-id={it.id}>
        <blockquote>&ldquo;{it.q}&rdquo;</blockquote>
        <cite>{it.cite}</cite>
      </div>
    );
  }

  if (it.kind === "whisper") {
    return (
      <div className="island whisper" style={style} data-id={it.id}>{it.text}</div>
    );
  }

  if (it.kind === "note") {
    return (
      <div className="island note" style={style} data-id={it.id}>{it.text}</div>
    );
  }

  if (it.kind === "field") {
    return (
      <div className="island field" style={style} data-id={it.id}>
        <div className="fig"><img src={it.img} alt=""/></div>
        <div className="cap">{it.cap}</div>
      </div>
    );
  }

  if (it.kind === "gloss") {
    return (
      <div className="island gloss" style={style} data-id={it.id}>
        <div className="term">{it.term}</div>
        <div className="def" dangerouslySetInnerHTML={{__html: it.def}}/>
      </div>
    );
  }

  if (it.kind === "method") {
    return (
      <div className="island method" style={style} data-id={it.id}>
        <ul>
          {it.steps.map((s,i)=>(
            <li key={i}>
              <span className="n">{String(i+1).padStart(2,"0")}</span>
              <div><p>{s}</p></div>
            </li>
          ))}
        </ul>
      </div>
    );
  }

  if (it.kind === "bib") {
    return (
      <div className="island bib" style={style} data-id={it.id}>
        <ol>
          {it.entries.map((e, i)=>(
            <React.Fragment key={i}>
              <span className="n">{String(i+1).padStart(2,"0")}</span>
              <span className="e" dangerouslySetInnerHTML={{__html:e}}/>
            </React.Fragment>
          ))}
        </ol>
      </div>
    );
  }

  if (it.kind === "colophon") {
    return (
      <div className="island colophon" style={style} data-id={it.id}>
        <p>Toister · Astarhan · 2026</p>
        <p><em>an open register. the field remains unbounded.</em></p>
        <p>set in Neue Haas Grotesk · Times · Courier</p>
      </div>
    );
  }

  if (it.kind === "cluster-head") {
    return (
      <div className="island cluster-head" style={style} data-id={it.id}>
        <div className="n">{it.n}</div>
        <div className="k">{it.k}</div>
      </div>
    );
  }

  if (it.kind === "thumb") {
    const a = it.a;
    return (
      <div className="island thumb" style={style} data-id={it.id}>
        <div className="plate"><Plate n={a.i}/></div>
        <div className="info">
          <div className="no">{String(a.i).padStart(3,"0")}</div>
          <div className="nm">{a.name}</div>
        </div>
      </div>
    );
  }

  if (it.kind === "spec") {
    const a = it.a;
    return (
      <div className="island spec" style={style} data-id={it.id}>
        <div className="plate"><Plate n={a.i}/></div>
        <div className="info">
          <div className="no">
            <span>{String(a.i).padStart(3,"0")}</span>
            <span>{a.y ?? "—"}</span>
          </div>
          <h3>{a.name}</h3>
          <p className="desc">{a.d}</p>
        </div>
      </div>
    );
  }

  if (it.kind === "viewer") {
    return (
      <div className="island viewer" style={style} data-id={it.id}>
        <div className="stage">
          <SAViewer
            specimenIndex={viewer.idx}
            setSpecimenIndex={viewer.setIdx}
            specimens={VIEWER_SPECIMENS}
            autoRotate={viewer.autoRotate}
          />
        </div>
        <div className="controls">
          <div className="spec">spec-{String(VIEWER_SPECIMENS[viewer.idx].i).padStart(4,"0")}</div>
          <div className="name">computed radiator — drag to orbit</div>
          <div className="buttons">
            <button onClick={()=>viewer.setIdx((viewer.idx - 1 + VIEWER_SPECIMENS.length) % VIEWER_SPECIMENS.length)}>◂</button>
            <button onClick={()=>viewer.setIdx((viewer.idx + 1) % VIEWER_SPECIMENS.length)}>▸</button>
          </div>
        </div>
      </div>
    );
  }

  return null;
}

// ───────────────────────────────────────────────────────────────────────────
// Threads — drawn as an SVG layer in plane coords.

function Threads({ islands, show }){
  // Compute centres of islands using ids
  const byId = {};
  for (const it of islands) byId[it.id] = it;
  function centre(it){
    // estimate visual height by kind
    const hByKind = {
      title: 360, prose: 180, pullquote: 200, whisper: 80, note: 80,
      field: 340, gloss: 130, method: 280, bib: 340, colophon: 160,
      "cluster-head": 280, thumb: 170, spec: 300, viewer: 580
    };
    const h = hByKind[it.kind] || 160;
    const w = it.w || 240;
    return { cx: it.x + w/2, cy: it.y + h/2 };
  }
  const paths = [];
  for (let i = 0; i < THREADS.length; i++){
    const [a, b] = THREADS[i];
    const A = byId[a]; const B = byId[b];
    if (!A || !B) continue;
    const p1 = centre(A); const p2 = centre(B);
    // Curved path via midpoint perpendicular offset
    const mx = (p1.cx + p2.cx) / 2;
    const my = (p1.cy + p2.cy) / 2;
    const dx = p2.cx - p1.cx, dy = p2.cy - p1.cy;
    const len = Math.max(1, Math.hypot(dx, dy));
    const nx = -dy / len, ny = dx / len;
    const bow = Math.min(260, len * 0.18) * ((i % 2) ? 1 : -1);
    const cxm = mx + nx * bow;
    const cym = my + ny * bow;
    const cls = (i % 3 === 0) ? "d" : (i % 3 === 1 ? "dd" : "");
    // Offset to plane origin (20000, 20000) because .threads is shifted
    const ox = 20000, oy = 20000;
    paths.push(
      <path key={i} className={cls}
        d={`M${p1.cx+ox} ${p1.cy+oy} Q${cxm+ox} ${cym+oy} ${p2.cx+ox} ${p2.cy+oy}`}/>
    );
  }
  if (!show) return null;
  return <svg className="threads">{paths}</svg>;
}

// ───────────────────────────────────────────────────────────────────────────
// Viewport — pan + zoom

function Viewport({ children, onPose }){
  const ref = React.useRef(null);
  const stateRef = React.useRef({ x: 0, y: 0, k: 0.85 });
  const [, force] = React.useReducer(x=>x+1, 0);

  // Centre on origin on mount
  React.useEffect(()=>{
    const el = ref.current;
    if (!el) return;
    const r = el.getBoundingClientRect();
    stateRef.current.x = r.width / 2;
    stateRef.current.y = r.height / 2;
    apply();
    force();
  }, []);

  function apply(){
    const el = ref.current;
    if (!el) return;
    const world = el.querySelector(".world");
    const s = stateRef.current;
    world.style.transform = `translate(${s.x}px, ${s.y}px) scale(${s.k})`;
    if (onPose) onPose(s);
  }

  React.useEffect(()=>{
    const el = ref.current;
    if (!el) return;
    let dragging = false, lx = 0, ly = 0;

    const onDown = (e) => {
      // Only pan if not on an interactive element
      const tgt = e.target;
      if (tgt.closest && tgt.closest("button,input,canvas")) return;
      dragging = true; lx = e.clientX; ly = e.clientY;
      el.classList.add("panning");
      el.setPointerCapture(e.pointerId);
    };
    const onMove = (e) => {
      if (!dragging) return;
      stateRef.current.x += (e.clientX - lx);
      stateRef.current.y += (e.clientY - ly);
      lx = e.clientX; ly = e.clientY;
      apply();
    };
    const onUp = (e) => {
      dragging = false;
      el.classList.remove("panning");
      try{ el.releasePointerCapture(e.pointerId) } catch(_){}
    };
    const onWheel = (e) => {
      if (e.target.closest && e.target.closest("canvas")) return;
      e.preventDefault();
      const r = el.getBoundingClientRect();
      const mx = e.clientX - r.left, my = e.clientY - r.top;
      const s = stateRef.current;
      const wx = (mx - s.x) / s.k;
      const wy = (my - s.y) / s.k;
      // zoom with wheel; shift+wheel = horizontal pan; ctrl+wheel also zoom
      if (e.ctrlKey || e.metaKey || !e.shiftKey) {
        const factor = Math.exp(-e.deltaY * 0.0015);
        s.k = Math.max(0.18, Math.min(2.4, s.k * factor));
        s.x = mx - wx * s.k;
        s.y = my - wy * s.k;
      } else {
        s.x -= e.deltaY;
        s.y -= e.deltaX;
      }
      apply();
    };
    const onKey = (e) => {
      const s = stateRef.current;
      const step = 120;
      if (e.key === "ArrowLeft")  { s.x += step; apply(); }
      if (e.key === "ArrowRight") { s.x -= step; apply(); }
      if (e.key === "ArrowUp")    { s.y += step; apply(); }
      if (e.key === "ArrowDown")  { s.y -= step; apply(); }
      if (e.key === "0")          { s.k = 0.85; apply(); }
      if (e.key === "+" || e.key === "=") { s.k = Math.min(2.4, s.k * 1.15); apply(); }
      if (e.key === "-")          { s.k = Math.max(0.18, s.k / 1.15); apply(); }
    };
    el.addEventListener("pointerdown", onDown);
    el.addEventListener("pointermove", onMove);
    el.addEventListener("pointerup", onUp);
    el.addEventListener("pointercancel", onUp);
    el.addEventListener("wheel", onWheel, { passive:false });
    window.addEventListener("keydown", onKey);
    return ()=>{
      el.removeEventListener("pointerdown", onDown);
      el.removeEventListener("pointermove", onMove);
      el.removeEventListener("pointerup", onUp);
      el.removeEventListener("pointercancel", onUp);
      el.removeEventListener("wheel", onWheel);
      window.removeEventListener("keydown", onKey);
    };
  }, []);

  // expose programmatic goTo
  React.useEffect(()=>{
    window.SA_goTo = (x, y, k) => {
      const el = ref.current; if (!el) return;
      const r = el.getBoundingClientRect();
      const s = stateRef.current;
      if (k) s.k = k;
      s.x = r.width/2 - x * s.k;
      s.y = r.height/2 - y * s.k;
      apply();
    };
  }, []);

  return (
    <div className="viewport" ref={ref}>
      <div className="world">{children}</div>
    </div>
  );
}

// ───────────────────────────────────────────────────────────────────────────
// App

function App(){
  const [t, setTweak] = useTweaks(TWEAK_DEFAULTS);
  const [idx, setIdx] = React.useState(0);
  const [pose, setPose] = React.useState({x:0, y:0, k:0.85});

  React.useEffect(()=>{
    document.body.setAttribute("data-density", t.density);
    document.body.setAttribute("data-grid", t.grid ? "1" : "0");
    document.body.setAttribute("data-numbering", t.numbering);
  }, [t.density, t.grid, t.numbering]);

  const viewer = {
    idx, setIdx,
    autoRotate: t.autoRotate
  };

  const jumps = [
    { label: "title",    x: 0,    y: 0 },
    { label: "essay",    x: 1400, y: 120 },
    { label: "specimen", x: 720,  y: 420 },
    { label: "archive",  x: 360,  y: 2200 },
    { label: "field",    x: -400, y: 500 },
    { label: "sources",  x: -1280, y: -80 },
  ];

  return (
    <>
      <Viewport onPose={setPose}>
        <div className="bg-grid"/>
        <div className="bg-axes"/>
        <Threads islands={ISLANDS} show={t.threads}/>
        {ISLANDS.map(it => <Island key={it.id} it={it} viewer={viewer}/>)}
      </Viewport>

      <header className="masthead">
        <div>Journal of Artistic Research · Research Catalogue</div>
        <div className="centre">Speculative Antennology</div>
        <div className="jar">exposition · open field · MMXXVI</div>
      </header>

      <div className="chrome">
        <div className="crop t"/><div className="crop b"/><div className="crop l"/><div className="crop r"/>

        <div className="jumpmenu">
          <div className="t">drift to →</div>
          {jumps.map(j => (
            <button key={j.label} onClick={()=>window.SA_goTo && window.SA_goTo(j.x, j.y, 0.85)}>
              {j.label}
            </button>
          ))}
        </div>

        <div className="help">
          <kbd>drag</kbd> pan · <kbd>wheel</kbd> zoom · <kbd>shift+wheel</kbd> pan · <kbd>0</kbd> reset
        </div>

        <div className="legend">
          <div className="row"><span className="sw t"/><span>island</span></div>
          <div className="row"><span className="sw"/><span>direct</span></div>
          <div className="row"><span className="sw d"/><span>associative</span></div>
        </div>

        <div className="compass" title="viewport position">
          <div className="vp"/>
          <div className="here" style={{
            left: (45 + (-pose.x / pose.k) / 90) + "px",
            top:  (45 + (-pose.y / pose.k) / 90) + "px"
          }}/>
          <div className="lbl">× {pose.k.toFixed(2)}</div>
        </div>
      </div>

      <TweaksPanel title="Tweaks">
        <TweakSection label="field"/>
        <TweakToggle label="show grid" value={t.grid}
          onChange={v=>setTweak("grid", v)}/>
        <TweakToggle label="show threads" value={t.threads}
          onChange={v=>setTweak("threads", v)}/>
        <TweakRadio label="density" value={t.density}
          options={["airy","regular","compact","archival"]}
          onChange={v=>setTweak("density", v)}/>
        <TweakRadio label="numbering" value={t.numbering}
          options={["arabic","roman","decimal"]}
          onChange={v=>setTweak("numbering", v)}/>
        <TweakSection label="specimen"/>
        <TweakToggle label="auto-rotate" value={t.autoRotate}
          onChange={v=>setTweak("autoRotate", v)}/>
      </TweaksPanel>
    </>
  );
}

window.SA_App = App;
